version: "3.9"

services:
  web:
    image: docker-project-web:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: dbcrud
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbcrud
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

volumes:
  mysql_data:

networks:
  app-net:
